website/views.py
#from asyncio.windows_events import NULL
from flask import Blueprint, jsonify, render_template, request, flash, redirect, url_for, make_response, Response
from flask_paginate import Pagination, get_page_parameter
from flask_login import login_required, current_user, AnonymousUserMixin
from sqlalchemy import null, func, asc, desc
from .models import Bankroll, Player, Alias, Game, Payment, Url, Earning, PokernowId, Behavior
from . import db
import json, requests, csv
from io import StringIO
from functools import wraps
import boto3
import os
from dotenv import load_dotenv
load_dotenv()


s3 = boto3.client('s3',
                    aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID'),
                    aws_secret_access_key= os.getenv('AWS_SECRET_ACCESS_KEY'),
					region_name='us-east-1'
                     )
BUCKET_NAME='pokermanager'
SLEEP_TIME = 3

def isfile_s3(key: str) -> bool:
	#return True
	s3_resource = boto3.resource('s3')
	bucket = s3_resource.Bucket(BUCKET_NAME)
	"""Returns T/F whether the file exists."""
	objs = list(bucket.objects.filter(Prefix=key))
	return len(objs) == 1 and objs[0].key == key

	#s3 = boto3.client('s3')
	#try:
	#	s3.head_object(Bucket=BUCKET_NAME, Key=key)
	#	return True
	#except ClientError:
	#	return False

views = Blueprint('views', __name__)

@views.route('/files', methods=['GET', 'POST'])
def files():
	s3_resource = boto3.resource('s3')
	my_bucket = s3_resource.Bucket(BUCKET_NAME)
	summaries = my_bucket.objects.all()
	return render_template('files.html', my_bucket=my_bucket, files=summaries)


def admin_required(f):
	@wraps(f)
	def decorated_function(*args, **kwargs):
		#print(current_user.admin)
		if current_user.is_anonymous:
			return redirect(url_for('auth.login'))
		if current_user and current_user.admin:
			return f(*args, **kwargs)
		else:
			return redirect(url_for('auth.login'))
	return decorated_function

def sub_required(f):
	@wraps(f)
	def decorated_function(*args, **kwargs):
		if current_user.is_anonymous:
			return redirect(url_for('auth.login'))
		if current_user and current_user.subscribed:
			return f(*args, **kwargs)
		else:
			return redirect(url_for('auth.login'))
	return decorated_function

def can_upload(f):
	@wraps(f)
	def decorated_function(*args, **kwargs):
		if current_user.is_anonymous:
			return redirect(url_for('auth.login'))
		if current_user and current_user.can_upload:
			return f(*args, **kwargs)
		else:
			return redirect(url_for('auth.login'))
	return decorated_function


@views.route('/home', methods=['GET', 'POST'])
def home():
	return render_template("home.html")


@views.route('/', methods=['GET', 'POST'])
def index():
	return redirect(url_for('views.games'))

#@views.route('/delete-note', methods=['POST'])
#def delete_note():
#	data = json.loads(request.data)
#	noteId = data['noteId']
#	note = Note.query.get(noteId)
#	if note:
#		if note.user_id == current_user.id:
#			db.session.delete(note)
#			db.session.commit()
#	return jsonify({})

@views.route('/players', methods=['GET','POST'])
def players():
	if request.method == 'POST':
		data = request.form
		player_name = data.get('player_name')
		player_venmo = data.get('player_venmo')
		player_alias = data.get('player_alias')

		player = Player.query.filter_by(name=player_name).first()
		alias = Alias.query.filter_by(alias=player_alias).first()

		if player:
			flash("This player already exists.", category='error')
		elif alias:
			flash("This player alias already exists.", category='error')
		elif(len(player_name) < 1):
			flash("Please enter a valid name.", category='error')
		else:
			new_player = Player(name=player_name, venmo=player_venmo)
			db.session.add(new_player)
			if player_alias:
				new_alias = Alias(alias=player_alias, player=new_player)
				db.session.add(new_alias)
			db.session.commit()
			flash('Player added', category='success')

	players = Player.query.order_by(Player.name.asc()).all()
	return render_template("players.html", user=current_user, players=players)


@views.route('/edit_player', methods=['GET','POST'])
@admin_required
def edit_player():
	player_id = request.args.get('player_id')
	if not player_id:
		flash("That user does not exist.", category="error")
		return redirect(url_for('views.players'))
	
	player = Player.query.filter_by(id=player_id).first()
	if not player:
		flash("That player does not exist.", category="error")
		return redirect(url_for('views.players'))
	
	if request.method == 'POST':
		data = request.form
		#print(data)
		if  "alias-submit" in request.form:
			print('alias submit')
			player_alias = data.get('player-alias')
			alias = Alias.query.filter_by(alias=player_alias).first()
			if len(player_alias) < 1:
				flash('Alias is too short.', category='error')
			elif alias:
				flash("This player alias already exists.", category='error')
			else:
				new_alias = Alias(alias=player_alias, player_id=player_id)
				db.session.add(new_alias)
				db.session.commit()
				flash('Alias added!', category='success')

		elif "player-submit" in request.form:
			print('player submit')
			player_name = data.get('player_name')
			player_id = data.get('player_id')
			player_venmo = data.get('player_venmo')
			if(len(player_name) < 1):
				flash("Please enter a valid name.", category='error')
			elif(len(player_id) < 1):
				flash("Invalid player.", category='error')
			else:
				update_player = Player.query.filter_by(id=player_id).first()
				update_player.name = player_name
				update_player.venmo = player_venmo
				db.session.commit()
				flash('Player added', category='success')
			

	return render_template("edit_player.html", user=current_user, player=player)

	

@views.route('/delete-alias', methods=['POST'])
@admin_required
def delete_alias():
	data = json.loads(request.data)
	aliasId = data['aliasId']
	alias = Alias.query.get(aliasId)
	if alias:
		db.session.delete(alias)
		db.session.commit()
	return jsonify({})


@views.route('/import_game', methods=['GET','POST'])
@can_upload
def import_game():
	if request.method == 'POST':
		data = request.form
		game_urls = []
		game_urls.append(data.get('game_url1'))
		if len(data.get('game_url2')) > 0:
			game_urls.append(data.get('game_url2'))
		if len(data.get('game_url3')) > 0:
			game_urls.append(data.get('game_url3'))
		new_game = False
		if len(game_urls) > 0:
			if len(game_urls[0]) == 0:
				flash("Please enter a valid URL.", category='error')
				return render_template("import_game.html", user=current_user)
			for game_url in game_urls:
				url = Url.query.filter_by(url=game_url).first()
				if url:
					flash("URL "+game_url+" has already been imported.", category="error")
					return render_template("import_game.html", user=current_user)
				else:
					if not new_game:
						if data.get('use_cents') == 'on':
							use_cents = 1
						else:
							use_cents = 0
						new_game = Game(settled=False, decimal=use_cents)
						db.session.add(new_game)
						db.session.flush()
					new_url = Url(url = game_url, game_id=new_game.id)
					db.session.add(new_url)
			db.session.commit()
			return redirect(url_for('views.link_players', game_id=new_game.id))
		else:
			flash("Please enter a URL.", category="error")

	return render_template("import_game.html", user=current_user)

@views.route('/link_players', methods=['GET','POST'])
@can_upload
def link_players():	
	processLedger = 0
	if request.method=='POST' and request.form.get('whichForm') == 'addPlayer':
		data = request.form
		player_name = data.get('player_name')
		player_venmo = data.get('player_venmo')
		player_alias = data.get('player_alias')

		player = Player.query.filter_by(name=player_name).first()
		alias = Alias.query.filter_by(alias=player_alias).first()

		if player:
			flash("This player already exists.", category='error')
		elif alias:
			flash("This player alias already exists.", category='error')
		elif(len(player_name) < 1):
			flash("Please enter a valid name.", category='error')
		else:
			new_player = Player(name=player_name, venmo=player_venmo)
			db.session.add(new_player)
			if player_alias:
				new_alias = Alias(alias=player_alias, player=new_player)
				db.session.add(new_alias)
			db.session.commit()
			flash('Player '+player_name+' added', category='success')
	elif request.method=='POST' and request.form.get('whichForm') == 'linkPlayers':
		data = request.form
		player_link = data.getlist('player_link')
		if '-1' in player_link:
			flash("Please link every player.", category="error")
		else:
			processLedger = 1

		
	game = Game.query.filter_by(id=request.args.get('game_id')).first()
	game_urls = game.urls


	from time import sleep
	if not game_urls:
		flash("Game URL is missing.", category="error")
		return redirect(url_for('views.import_game'))

	csv_dicts = []
	for game_url in game_urls:
		#####################################
		#GAME SETUP
		#####################################
		#game_url = 'https://www.pokernow.club/games/pglvS2nnCbYnGCfk17JdkB11_' #full game
		#game_url = 'https://www.pokernow.club/games/pglOLqx5yJYOEQGxL-BRzxeDp' #test game
		game_url_split = game_url.url.split('/')
		game_id = game_url_split[-1]
		ledger_url = game_url.url + '/ledger_' + game_id + '.csv'
	
		#####################################
		#LOAD THE GAME, ERROR IF FAILED
		#####################################
		from botocore.exceptions import ClientError
		ledger_contents = []
		try:
			sleep(SLEEP_TIME)
			#r = requests.get(ledger_url, verify=False, timeout=10, stream=True)
			r = requests.get(ledger_url, verify=False, timeout=10)
			
			#for line in r.iter_lines():
			#	if line:
			#		ledger_contents.append(line.decode('UTF-8'))
			#import urllib.request

website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="static/style.css"
    />
    <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
        ></script>
    <title>{% block title %}Home{% endblock %}</title>
    {% block extra_header %}
    
    {% endblock %}
    </head>
    <body class="body">
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #3fa76c;">
            <div class="container-fluid" style="max-width: 1140px;margin-right:auto;margin-left:auto">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar" aria-controls="mainNavbar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <a class="navbar-brand" href="/">&spades; POKER MANAGER</a>
                <div class="collapse navbar-collapse justify-content-start" id="mainNavbar">
                    <div class="navbar-nav">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            
                            <li class="nav-item" align="center"><a class="nav-link" id="nav-players" href="/players"><i class="fa fa-user" aria-hidden="true"></i><br/>Players</a></li>
                            {% if user and  user.is_authenticated and user.can_upload %}
                            <li class="nav-item" align="center"><a class="nav-link" id="nav-import-game" href="/import_game"><i class="fa fa-upload" aria-hidden="true"></i><br/>Import Game</a></li>
                            {% endif %}
                            <li class="nav-item" align="center"><a class="nav-link" id="nav-import-game" href="/games"><i class="fa fa-database" aria-hidden="true"></i><Br/>Games</a></li>
                            {% if user and  user.is_authenticated and user.player_id and user.subscribed %}
                            <li class="nav-item" align="center"><a class="nav-link" id="nav-import-game" href="/player_stats"><i class="fa fa-pie-chart" aria-hidden="true"></i><br/>Stats</a></li>
                            <!--<li class="nav-item" align="center"><a class="nav-link" id="nav-import-game" href="/player_stats"><i class="fa fa-usd" aria-hidden="true"></i><br/>Bankroll</a></li>-->
                            {% endif %}
                        </ul>
                    </div>
                    <div class="navbar-nav ml-auto" style="margin-left: auto">
                       <a href="https://account.venmo.com/u/MattMuoio" target="_blank" class="btn btn-warning"><b>$ Donate</b></a>
                    </div>
                    <div class="navbar-nav ml-auto" style="margin-left: auto">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            {% if user and  user.is_authenticated %}
                            
                            <div class="dropdown">
                                <button class="btn btn-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{user.first_name}} {{user.last_name}}
                                </button>
                                <ul class="dropdown-menu dropdown-menu-lg-end">
                                    <li><a class="dropdown-item" href="/edit_user">Edit Profile</a></li>
                                    {% if user and  user.is_authenticated and user.admin %}
                                    <li><a class="dropdown-item" href="/manage_users">Manage Subs</a></li>
                                    {% endif %}
                                    <li><a class="dropdown-item" id="nav-logout" href="/logout">Logout</a></li>
                                </ul>
                            </div>

                            
                            {% else %}
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item"><a class="nav-link" id="nav-signUp" href="/sign-up">Sign Up</a></li>
                                <li class="nav-item"><a class="nav-link" id="nav-login" href="/login">Login</a></li>
                            </ul>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </nav>



        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            {% if category == 'error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close pull-right" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% elif category == 'success' %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close pull-right" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endif %}
            {% endfor %}
        {% endif %}
        {% endwith %}


        <br/>

        <div class="container h-100 body_container" style="max-width:1140px; background-color: #fff;">
            {% block content %}
            
            {% endblock %}
        </div>



        
        <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
        ></script>
        <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

        <script type="text/javascript"
            src="{{ url_for('static', filename='index.js') }}"
        ></script>
        
    </body>
</html>

website/templates/batch_import_logs.html
{% extends "base.html" %}
{% block title %}Games{% endblock %}

{% block content %}

	{% for log in logs %}
	{{log}}<br/>
	{% endfor %}

	<br/><br/>


	{% for ledger in ledgers %}
	{{ledger}}<br/>
	{% endfor %}

{% endblock %}


website/templates/edit_user.html
{% extends "base.html" %}
{% block title %}Edit Player{% endblock %}

{% block content %}

<h1 align="center">Edit User</h1>


<form method="POST">
    <div class="form-group">
        <!--<label for="email">Email Address</label>-->
        <input type="email" class="form-control" id="email" name="email" placeholder="Email" value="{{user.email}}"/>
    </div><br/>
    <div class="form-group">
        <!--<label for="firstName">First Name</label>-->
        <input type="text" class="form-control" id="firstName" name="firstName" placeholder="First name" value="{{user.first_name}}"/>
    </div><br/>
    <div class="form-group">
        <!--<label for="lastName">Last Name</label>-->
        <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Last name" value="{{user.last_name}}"/>
    </div><br/>
	<h4>Reset Password (optional)</h4>
    <div class="form-group">
        <!--<label for="password1">Password</label>-->
        <input type="password" class="form-control" id="password1" name="password1" placeholder="New password"/>
    </div><br/>
    <div class="form-group">
        <!--<label for="password2">Confrim Password</label>-->
        <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password"/>
    </div>
    <br/>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>



{% endblock %}

website/templates/home.html
{% extends "landing.html" %}
{% block title %}Home{% endblock %}

{% block content %}
asdf
{% endblock %}

website/templates/import_game.html
{% extends "base.html" %}
{% block title %}Import Game{% endblock %}

{% block content %}
<h1 align="center">Import Game</h1>
	
	<form method="POST">
	<div class="form-control mb-3">
	<label for="game_url" class="form-label">Game URL(s):</label>
	<input type="text" name="game_url1" id="game_url" class="form-control"></input><br/>
	<input type="text" name="game_url2" id="game_url" class="form-control" placeholder="(Optional)"></input><br/>
	<input type="text" name="game_url3" id="game_url" class="form-control" placeholder="(Optional)"></input><br/>

	
	<div align="center">
		<input type="checkbox" name="use_cents" id="use_cents" ></input>
		<label for="use_cents" class="form-label">Use cents</label><br/><br/>
		<button type="submit" class="btn btn-primary">Load URL</button>
	</div>
	</div>
</form>

{% endblock %}

website/templates/import_log.html
{% extends "base.html" %}
{% block title %}Import Logs{% endblock %}

{% block content %}
<h1 align="center">Import Logs</h1>

<div id="no-more-tables">
	<table class="table table-striped">
		<thead>
		<tr>
			<th scope="col">DATE</th>
			<th scope="col">URLS</th>
			<th scope="col" style="text-align:center">TYPE</th>
			<th scope="col" style="text-align:center">IMPORTED</th>
			{% if user and user.is_authenticated and user.admin %}
			<th scope="col" style="text-align:center">ACTIONS</th>
			{% endif %}
		</tr>
		</thead>
		<tbody>
		{% for url in game.urls %}
			<tr>
				<td style="vertical-align: middle;">{{ game.date.strftime("%m/%d/%Y") }}</td>
				<td style="vertical-align: middle;">
					{{url.url}}
				</td>
				<td align="center" style="vertical-align: middle;">NLHE</td>
				<td align="center" style="vertical-align: middle;">
					{% if url.imported %}<i class="fa fa-check-circle-o text-success" style="font-size:20pt" aria-hidden="true"></i>{% else %}<i class="fa fa-times-circle-o text-danger" style="font-size:20pt" aria-hidden="true"></i>{% endif %}
				</td>
				{% if user and user.is_authenticated and user.admin %}
				<td align="center" style="vertical-align: middle;">
					{% if user and user.is_authenticated and user.admin %}
					
					{% if not url.imported %}
					<a href="#" class="btn btn-sm btn-outline-secondary disabled" data-bs-toggle="modal" data-bs-target="#confirmDelete_{{url.id}}" data-toggle="tooltip" data-placement="top" title="Delete Log"><i class="fa fa-trash" aria-hidden="true"></i></a>
					{% else %}
					<a href="#" class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#confirmDelete_{{url.id}}" data-toggle="tooltip" data-placement="top" title="Delete Log"><i class="fa fa-trash" aria-hidden="true"></i></a>
					{% endif %}
					{% endif %}
				</td>
				{% endif %}
			</tr>

			<div class="modal fade" id="confirmDelete_{{url.id}}" tabindex="-1" aria-labelledby="confirmDelete_{{url.id}}Label" aria-hidden="true">
				<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
					<h5 class="modal-title" id="confirmDelete_{{url.id}}Label">Delete this log?</h5>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>
					<div class="modal-body text-wrap">
						<b>{{ game.date.strftime("%m/%d/%Y") }}</b><br/>
							<i>{{url.url}}</i><br/>
					</div>
					<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
					<a href="{{url_for('views.delete_log', url_id=url.id)}}" type="button" class="btn btn-primary" >Delete Log</a> <!--FIX THIS TO BE FOR LOGS, NOT GAMES-->
					</div>
				</div>
				</div>
			</div>
		{% endfor %}
	</tbody>
	</table>
</div>

<script type="text/javascript">
	$(document).ready(function () {
		//$(function () {
			$('[data-toggle="tooltip"]').tooltip()
		//})
	});
  </script>

<form method="POST" 
enctype = "multipart/form-data">
<div class="form-control mb-3"><br/>
<input class="form-control" type="file" name="file[]" multiple />
<br/>
<div align="center">
	<button type="submit" class="btn btn-primary">Upload File</button>
</div>
<br/>
</div>
</form>  




{% endblock %}


website/templates/login.html
{% extends "base.html" %}
{% block title %}Log In{% endblock %}

{% block content %}

<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group mb-3">
        <label for="email" class="form-label">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email"/>
    </div>
    <div class="form-group mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password"/>
    </div>
    <br/>
    <button type="submit" class="btn btn-primary">Login</button>
</form>

{% endblock %}

website/templates/manage_users.html
{% extends "base.html" %}
{% block title %}Manage Users{% endblock %}

{% block content %}
<h1 align="center">Manage Users</h1>

<table class="table">
	<thead>
	  <tr>
		<th scope="col">NAME</th>
		<th scope="col">VENMO</th>
		<th scope="col">ALIAS</th>
		<th scope="col">SUBSCRIBED</th>
		<th scope="col">EXPIRATION</th>
		<th scope="col">CANCEL SUB</th>
		<th scope="col">ADD 30 DAYS</th>
	  </tr>
	</thead>
	<tbody>
	{% if users %}
	{% for user in users %}
		<tr style="vertical-align: middle">
			<td><strong>{{ user.first_name }} {{ user.last_name }}</strong></td>
			<td>{{ user.player.venmo }}</td>
			<td>
				{% for alias in user.player.aliases %}
				<span class="badge rounded-pill bg-secondary">{{ alias.alias }}</span>
				{% endfor %}
			</td>
			<td>{{user.subscribed}}</td>
			<td {% if user.expires_on <= today %}class="text-danger"{% endif %}>{{user.expires_on.strftime('%a, %b %d, %Y')}}</td>
			<td align="center">
				<button type="button" class="btn btn-danger" onClick="expireSub({{user.id}})">X</button>
			</td>
			<td align="center">
				<button type="button" class="btn btn-primary" onClick="add30Days({{user.id}})">+30</button>
			</td>
		</tr>
	{% endfor %}
	{% endif %}
</tbody>
</table>
	




{% endblock %}

website/templates/players.html
{% extends "base.html" %}
{% block title %}Players{% endblock %}

{% block content %}
<h1 align="center">Players</h1>

<div id="no-more-tables">
	<table class="table">
		<thead>
		<tr>
			<th scope="col">NAME</th>
			<th scope="col">VENMO</th>
			<th scope="col">ALIAS</th>
			{% if user and user.is_authenticated and user.admin %}
			<th scope="col" align="center">NET</th>
			{% endif %}
		</tr>
		</thead>
		<tbody>
		{% if players %}
		{% for player in players %}
			<tr>
				<td><a href="{{url_for('views.edit_player', player_id=player.id)}}" ><strong>{{ player.name }}</strong></a></td>
				<td>{{ player.venmo }}</td>
				<td>
					{% for alias in player.aliases %}
					<span class="badge rounded-pill bg-secondary">{{ alias.alias }}</span>
					{% endfor %}
				</td>
				{% if user and user.is_authenticated and user.admin %}
				<td align="center">
					{% if player.earnings | sum(attribute='net') != 0 %}
					{{ "{:,.2f}".format(player.earnings | sum(attribute='net')) }}
					{% endif %}
				</td>
				{% endif %}
			</tr>
		{% endfor %}
		{% endif %}
	</tbody>
	</table>
</div>



<br/>
<form method="POST">
	<div class="form-control mb-3">
	<label for="player_name" class="form-label">Player Name</label>
	<input type="text" name="player_name" id="player_name" class="form-control"></input>
	<br/>
	<label for="player_venmo" class="form-label">Venmo</label>
	<input type="text" name="player_venmo" id="player_venmo" class="form-control"></input>
	<br/>
	<label for="player_alias" class="form-label">Alias</label>
	<input type="text" name="player_alias" id="player_alas" class="form-control"></input>
	<br/>
	<div align="center">
		<button type="submit" class="btn btn-primary">Add Player</button>
	</div>
	</div>
</form>

{% endblock %}

website/templates/profile.html
{% extends "base.html" %}
{% block title %}Profile - {{user.first_name}} {{user.last_name}}{% endblock %}

{% block content %}
	<br/>
	<a href="/edit_user" class="link-dark pull-right" onClick=""><i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i></a>

	<div class="profile-icon" style="float: left;margin-right:15px;"><i class="fa fa-user-circle fa-4x" aria-hidden="true"></i></div>
	<div style="font-size: 16pt;">
		<b>{{user.first_name}} {{user.last_name}}</b><br/>
		{{user.email}}
   </div>
   <hr/>
   {% if player %}
   <h3>Player info:</h3>
   Name: {{player.name}}<br/>
   Venmo: {{player.venmo}}<br/>
   Winnings: {{net}}



   {% endif %}
{% endblock %}

website/templates/signup.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}

{% block content %}

<form method="POST">
    <h3 align="center">Sign Up</h3><br/>
    <div class="form-group">
        <!--<label for="email">Email Address</label>-->
        <input type="email" class="form-control" id="email" name="email" placeholder="Email"/>
    </div><br/>
    <div class="form-group">
        <!--<label for="firstName">First Name</label>-->
        <input type="text" class="form-control" id="firstName" name="firstName" placeholder="First name"/>
    </div><br/>
    <div class="form-group">
        <!--<label for="lastName">Last Name</label>-->
        <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Last name"/>
    </div><br/>
    <div class="form-group">
        <!--<label for="password1">Password</label>-->
        <input type="password" class="form-control" id="password1" name="password1" placeholder="Password"/>
    </div><br/>
    <div class="form-group">
        <!--<label for="password2">Confrim Password</label>-->
        <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password"/>
    </div><br/>
    <div class="form-group">
		<select name="player_id" class="form-select mb-2">
			<option value="-1">Select player (optional)</option>
			{% if players %}
			{% for player in players %}
                {% if not player.user %}
			<option value="{{player.id}}">{{player.name}}</option>
                {% endif %}
			{% endfor %}
			{% endif %}

		</select>
    <br/>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}